### ISSUE TITLE
Using more than one backend service

### ISSUE THREAD

**Issue by greyslater** [smashwilson/lets-nginx#13]
Hi,

great work but the update for using more than one backend is not working for me.
When I use more then one backend I get:

> Requested domain is not a FQDN

afaik the domain names are OK - i get my public ip when performing nslookup from docker-host

any ideas?

**Comment by greyslater** [comment]
I'm sorry...!
forgot to pull the new image from docker

**Comment by greyslater** [comment]
but now i get:

> /entrypoint.sh: line 88: d: unbound variable

I already made new volumes so there are no cached certificates or whatever

**Comment by smashwilson** [comment]
Yeah, I was a little too quick on the merge button with that PR I'm afraid - @jbtrystram is working on a fix in #12.

**Comment by greyslater** [comment]
I see...
is there a way to get it done or will it always break the letsencrypt 5-certs-a-week limit?

**Comment by smashwilson** [comment]
It's a little tricky but it's doable I think. (I actually misread the earlier comment at first.)

**Comment by jbtrystram** [comment]
It's fixed now. Can you update the image and confirm it works for you? It's OK on my system but I'd like another feedback on this ;)

**Comment by greyslater** [comment]
well done, works great

**Comment by smashwilson** [comment]
Excellent. Thanks for the fix, @jbtrystram!
