### ISSUE TITLE
Error 500 when trying to send POST request

### ISSUE THREAD

**Issue by jbtrystram** [smashwilson/lets-nginx#14]
Hello,

I get an error 500 whenever i try to upload .torrent files to an http backend served via nginx. 
`[crit] 49#0: *562 open() "/var/lib/nginx/tmp/client_body/0000000047" failed (13: Permission denied),`

A simple solution is : 

```
docker exec -ti nginx bash
chmod +x -R /var/lib/nginx/
```

But it works only temporary.
After digging a bit it's look like this is due to the caching function. I'm not expert with thoses caching-functions. Is it necessary ?

**Comment by cadesalaberry** [comment]
I am having the same issue here.

Still working on it.
