### ISSUE TITLE
Add option to define default conf

### ISSUE THREAD

**Issue by jboesl** [smashwilson/lets-nginx#22]
In case someone accesses the server by entering ip address the first conf file in the vhost directory defines the server that is served. 
I'd like to be able to add a default.conf file that is used instead.

**Comment by jbtrystram** [comment]
Hi,

Simply create your default.conf file and a docker file : 

```
   FROM smashwilson/lets-nginx

   ADD default.conf /templates/nginx.conf
```

then `docker build .`

and here you go :)

**Comment by jboesl** [comment]
I don't even have to build my own image. I can simply add the templates directory as a volume and add the nginx.conf there. 
To define a default host I had to include one vhosts/<name>.conf file before 'include vhosts/*.conf' is loaded. 
So this one is resolved for me. Thanks.
