### ISSUE TITLE
automated renewal doesn't works

### ISSUE THREAD

**Issue by jbtrystram** [smashwilson/lets-nginx#28]
my cert just expired, so it looks like the cron task doesn't works.
I'll do some more tests

**Comment by jboesl** [comment]
I just got an e-mail notification from Let's Encrypt:

> Your certificate (or certificates) for the names listed below will expire in 19 days ...

I guess the certificates aren't properly renewed here, too.

**Comment by jbtrystram** [comment]
yes i noticed that in August. The renewal process isn't working properly. 
We need to use an init system and launch the cron manager for this to work . I haven't took the time to dig into it, but that's still on my to-do ;)

**Comment by bdito** [comment]
The renewall script didn´t worked for me.
After a little debugging I found out that the renewall script "/etc/periodic/monthly/reissue" uses the webroot-path "/etc/letsencrypt/webrootauth/" which doesn´t exist. After creating the directory manually the script worked.

I recommend you to add something like "mkdir -p /etc/letsencrypt/webrootauth/" to your script.

**Comment by jbtrystram** [comment]
that directory is indeed never created ! Thanks for the tip :)
