### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by giany** [smashwilson/lets-nginx#32]
When I try to run your image I get this:

Provided domains
mydomain.horse
Services to reverse-proxy
backend:8080
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
..............................................................................................................................+........................................................................................................................+..................+...............................................................................................+............................................+................................+..............................................................................................................+.............................................................................................................+............................................................................................................................................................................+...............................+..................................+.....................................................................................................................................................................................................................................................................................................................................................................................................+...................................................................................++_++_
Rendering template of nginx.conf
Rendering template of mydomain.horse in /etc/nginx/vhosts/mydomain.horse.conf
The SAN list has changed, removing the old certificate and ask for a new one.
An unexpected error occurred:
Bug in pythondialog: expected an empty output from u'infobox', but got: u'Error opening terminal: unknown.\n'Please see the logfile 'certbot.log' for more details.

**Comment by jbtrystram** [comment]
Looks like the letsencrypt script got an error..
Cn you provide some details about how you ran this ? (docker run full command, docker version)

Thanks !

**Comment by bponi** [comment]
I got the same issue when trying to renew my cert monthly.
I think you can solve this by adding `--text` parameter to the `letsencrypt certonly ...` command behind the `--expand` parameter in lines 122 and 148 from entrypoint.sh.

**Comment by jbtrystram** [comment]
@bponi, yep looks like you are right.. They broke backward compatibility :( 
This needs a bit of testing

**Comment by giany** [comment]
@bponi, that helped. Thanks.

**Comment by jbtrystram** [comment]
fixed.
