### ISSUE TITLE
Upgrade to certbot

### ISSUE THREAD

**Issue by jbtrystram** [smashwilson/lets-nginx#33]
The letsencrypt client had been renamed to certbot [1] and the certbot is packaged for alpine [2]

We should take that into account as the 'old' letsencrypt client may not be maintained in the long term.. 

Also, the certbot have now a plugin to autoconfigure nginx : that might worth a try ! [3]
[1] https://certbot.eff.org/about/
[2] https://pkgs.alpinelinux.org/package/edge/community/armhf/certbot
[3] https://certbot.eff.org/docs/using.html#nginx

**Comment by jbtrystram** [comment]
done by @itzg 
https://github.com/smashwilson/lets-nginx/pull/34

**Comment by itzg** [comment]
It would still be cool to address [3]
