### ISSUE TITLE
$STAGING=0 but Letsencrypt still issues a fake certificate

### ISSUE THREAD

**Issue by joelcapitao** [smashwilson/lets-nginx#38]
Hey

I'm trying to provision an application with ansible and I use your beautiful docker to reverse proxy several applications.
My ansible playbook uses a file in which all the variables are together. In this file, I put all the lets-nginx's docker variables.
I did my tests with the variable STAGING set to 1. Then, I set the variable to 0 in production but letsencrypt still issued a fake certificate : "CN=Fake LE Intermediate X1"
The issue : I thought the var STAGING was a "boolean", but it's not. It's a minor bug, not a big deal :) 
I will submit a MR very soon with a more specific condition to respect the doc.

Jo

**Comment by jbtrystram** [comment]
Cheers ! :+1:

**Comment by jbtrystram** [comment]
this make the setup script fail when the STAGING env variable is not set, since the script  is executed with `set -euo pipefail`. 

Thus it break compatibility.
