### ISSUE TITLE
Stuck at "This is going to take a long time"

### ISSUE THREAD

**Issue by dalareo** [smashwilson/lets-nginx#41]
Hi! I am very happy with this project, far more easy to use that proxy-companion stuff. I am using it with no problem with my Rancher deployment but when trying to integrate it with my Go app (Gogs) I get:

```
lets-nginx_1  | Services to reverse-proxy
lets-nginx_1  | gogs:3000
lets-nginx_1  | Generating DH parameters, 2048 bit long safe prime, generator 2
lets-nginx_1  | This is going to take a long time
```
But no certificated is setup... any help!!

**Comment by jbtrystram** [comment]
why not deploy only one container that proxies the two other services ?

**Comment by dalareo** [comment]
@jbtrystram I finally solved it using backend:3000 and not gogs:3000 as upstream. It is strange because it is not the same as the other installation (the Rancher one) in which I used the name of the container
I don't think I understand you suggestion!
