### ISSUE TITLE
"Account creation on ACMEv1 is disabled." error

### ISSUE THREAD

**Issue by nilgundag** [smashwilson/lets-nginx#47]
We recently started to get the following error on our servers. Is there a fix to this problem?

```
lets-nginx_1  | The SAN list has changed, removing the old certificate and ask for a new one.
lets-nginx_1  | Running initial certificate request...
lets-nginx_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
lets-nginx_1  | Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
lets-nginx_1  | An unexpected error occurred:
lets-nginx_1  | The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
lets-nginx_1  | Please see the logfiles in /var/log/letsencrypt for more details.
```

Thanks in advance,

**Comment by jbtrystram** [comment]
Hello,

It appears that alpine stable packages doesn't have a recent enough version of certbot...
I made a working version with acme.sh (https://github.com/Neilpang/acme.sh) on this branch : https://github.com/smashwilson/lets-nginx/tree/acme.sh

Feel free to build it as the dockerhub autobuild is not configured..

**Comment by arminus** [comment]
This fails for me towards the end. I run this with DOMAIN env set to multiple domains, it seems te get the certificate (at least one) ok, then fails with the following messages (domain names anonymized):

`[Tue Feb 11 10:53:57 UTC 2020] Your cert is in  /root/.acme.sh/d1.example.com/d1.example.com.cer ,
[Tue Feb 11 10:53:57 UTC 2020] Your cert key is in  /root/.acme.sh/d1.example.com/d1.example.com.key ,
[Tue Feb 11 10:53:57 UTC 2020] The intermediate CA cert is in  /root/.acme.sh/d1.example.com/ca.cer ,
[Tue Feb 11 10:53:57 UTC 2020] And the full chain certs is there:  /root/.acme.sh/d1.example.com/fullchain.cer ,
Installing the certificates,
[Tue Feb 11 10:53:57 UTC 2020] Unknown parameter :  -d d1.example.com  -d d2.example.com  -d d3.example.com ,`

I assume acme.sh --install-cert does not accept multiple -d arguments, hence the flow logic in entrypoint.sh doesn't work for multiple domains as it is right now?

**Comment by jbtrystram** [comment]
Oh I ran into the same issue and fixed that, but i just forgot to push that last commit, sorry about that. I just updated the branch now. 
Let me know if that works for you

**Comment by arminus** [comment]
The last commit on https://github.com/smashwilson/lets-nginx/commits/acme.sh was 14 days ago, that's what I already have - i.e. I don't see the commit you just mentioned?

**Comment by arminus** [comment]
Ok, there now and it works for multiple domains now. Thanks a lot!

**Comment by smashwilson** [comment]
Thanks @jbtrystram! 🌠

**Comment by finestructure** [comment]
I've been using this approach to fix the ACMEv1 issue with acme.sh successfully as a workaround - thanks for sharing it, @jbtrystram !

There are a couple of concerns I have about the process. Looking through the script I noticed:

```
curl -sS https://get.acme.sh -o acme.sh
```

and

```
/bin/bash acme.sh --upgrade --auto-upgrade
```

I'd rather avoid piping curl into a shell, especially in a container where it might get re-run at some much later stage. Even if a MITM injecting malicious code might be unlikely when run from a data centre, if that curl fails the container startup fails. Having your reverse-proxy fail to launch is not fun 😅

Regarding the `acme.sh --upgrade --auto-upgrade`: It has its charms to perhaps not have to worry about updating the script but it also means there's no version pinning. I.e. I can't easy go back to last month's working version.

I've tried to bake/freeze acme.sh into the image by running the installer and adding the output but that setup then failed to obtain certificates.

How are others dealing with this?

**Comment by jbtrystram** [comment]
@finestructure my preferred solution is to wait for the certbot client supporting ACMEv2 to be available in alpine:stable. 
As this point we should be able to simply switch back to master. 
That's why i did not merge this branch, I consider this acme script as a workaround.

@smashwilson WDYT ?

**Comment by finestructure** [comment]
Mmmm, if that's all it takes I might try swapping out `nginx:alpine` for just plain `nginx`. It's 100MB more but that might end up with a very small diff that's easy enough to roll back later. Or is that something you've tried already and won't work for some reason?

**Comment by finestructure** [comment]
I've just switched over to the `nginx` base image and that seems to work just fine. The changes are minimal: https://github.com/finestructure/lets-nginx/commit/3271e72667f7327bc300aad82fcdbefde9b3b57e

The only downside is an increase of ~100MB for the nginx image (~200MB vs 100MB).

**Comment by jbtrystram** [comment]
@finestructure please open a PR with that :)

**Comment by smashwilson** [comment]
Oh, yeah, that sounds totally fine to me :+1:

**Comment by finestructure** [comment]
There you go :)
